// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvztvonyrwbevrvtcmql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2enR2b255cndiZXZydnRjbXFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NTk2OTYsImV4cCI6MjA2NDEzNTY5Nn0.7IgjunjCJ4UgwBRJZVI9t49uTVQ2KKchCEk7kial5F0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);